# Generated by Django 6.1.1 on 2026-09-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_chambre', models.CharField(choices=[('single', 'Simple'), ('double', 'Double'), ('suite', 'Suite')], max_length=20)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('capacity', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('disponibility', models.BooleanField(default=True)),
            ],
        ),
    ]
